# Generated by Django 2.1.5 on 2019-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='书名')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('book_time', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
            },
        ),
    ]
